### ISSUE TITLE
Build on save not work when i quit atom from the session

### ISSUE THREAD

**Issue by mrdawn** [thomasjo/atom-latex#200] opened 2016-08-06 20:17 UTC
El Capitan 10.11.6
Atom 1.9.6
Latex 0.34.1

When i  quit atom (command + Q) and reopen with session (save the same tabs), build on save not work.
But when i reopen within open tabs, it's work.
Sorry for my english, i record a video [here](https://youtu.be/5ZEo1fhJVoo)
Update: i check with atom 1.8, 1.9.2 its working. Issue in version 1.9.4-1.9.6

**Comment by yitzchak** [comment] 2016-08-07 12:35
I can confirm this in v1.9.5.  It looks like the package is not getting activated upon session restore. Seems like the activation hook `language-latex:grammar-used` is not getting sent even if the active tab is a LaTeX file on session restore. Looks like package activation can be forced by opening a LaTeX file in another tab of doing a build.

**Comment by thomasjo** [comment] 2016-08-10 13:44
This bug was introduced in Atom core back in april (see atom/atom#11603), and will be fixed in Atom v1.9.8. Thanks to @nwolverson for reporting the issue in core, and @yitzchak for finding said issue.

**Closed by thomasjo** 2016-08-10 13:44 UTC
