### ISSUE TITLE
Object.dirname is deprecated.

### ISSUE THREAD

**Issue by mathuin** [thomasjo/atom-latex#386] opened 2017-06-15 11:24 UTC
Argument to `path.dirname` must be a string
```
Object.dirname (/opt/atom/resources/app/src/electron-shims.js:9:10)
new LogParser (/home/jmt/.files/atom/.atom/packages/latex/lib/parsers/log-parser.js:61:42)
KnitrBuilder.getLogParser (/home/jmt/.files/atom/.atom/packages/latex/lib/builder.js:83:14)
KnitrBuilder.parseLogFile (/home/jmt/.files/atom/.atom/packages/latex/lib/builder.js:68:27)
KnitrBuilder.parseLogAndFdbFiles (/home/jmt/.files/atom/.atom/packages/latex/lib/builder.js:181:12)
Composer.<anonymous> (/home/jmt/.files/atom/.atom/packages/latex/lib/composer.js:279:17)
```

**Comment by yitzchak** [comment] 2017-06-15 11:42
Thanks for the issue report. What version of the latex package are you using?

**Comment by mathuin** [comment] 2017-06-15 13:06
0.44.0 is the version I am using.

**Comment by yitzchak** [comment] 2017-06-19 13:21
I have not been able to reproduce this yet. Do you have an example file that this reliably happens with? Also, can you give a run-down of your settings are for the latex package?

**Comment by mathuin** [comment] 2017-06-19 18:34
I was unable to reproduce the issue myself.

```
"*":
  core:
    customFileTypes:
      "text.tex.latex": [
        "Rnw"
      ]
  latex:
    engine: "xelatex"
```

That's the only bit in my config.json that appears to be relevant.

**Comment by yitzchak** [comment] 2017-06-19 19:19
Ok. I think it might have happened because the log file was there, but the generated LaTeX file was not. I'll stick in a guard conditional just in case and close the issue afterward.

Just FYI, there is a syntax package ([language-knitr](https://atom.io/packages/language-knitr)) for knitr so you don't have to use the `customFileTypes` hack if you don't want to.

**Comment by mathuin** [comment] 2017-06-19 21:37
Thanks for the pointer!  I'm giving that package a try now -- so far all I see is the highlighting from the start lines, but I'm going to check out the docs to see what more it offers.  Thank you also for finding the problem and fixing it!

**Comment by yitzchak** [comment] 2017-06-19 23:37
It depends on [language-latex](https://atom.io/packages/language-latex) so you will need to have that installed also.

**Closed** 2017-08-03 15:46 UTC
Labels: needs reproduction
