### ISSUE TITLE
latexmk stopped working abruptly

### ISSUE THREAD

**Issue by BNasmith** [thomasjo/atom-latex#494] opened 2018-10-31 02:25 UTC
Hello,
I've been using atom-latex for over a year now, and for several weeks on my most recent installation of atom. A couple days ago, it abruptly stopped working and I'm not sure why. If I try to compile any latex document, including one as simple as, `testing.tex`:
```
\documentclass{article}

\begin{document}
Testing
\end{document}
```
I get the following message:
```
Texification failed with status code 2 and output of "Latexmk: This is Latexmk, John Collins, 7 August 2018, version: 4.59.
Latexmk: Filename `C:\Users\[.....]\Dropbox\github\PhD-Notes\Comprehensives\testing.tex' contains character not allowed for Tex file.
Latexmk: Stopping because of bad filenames(s).
```
This seems strange since I also have TexLive installed on my Windows Subsystem for Linux, and am able to run the latexmk installed there on this file without any trouble. 

Any ideas? Thank you,

**Comment by thomasjo** [comment] 2018-10-31 08:59
Thanks for the report, and sorry about the inconvenience! This seems like a duplicate of #480, so I will close this issue. Please follow #480 if you want updates on the progress.

**Closed by thomasjo** 2018-10-31 08:59 UTC
