### ISSUE TITLE
Glossary

### ISSUE THREAD

**Issue by lordblendi** [thomasjo/atom-latex#210] opened 2016-09-09 11:04 UTC
I couldn't find a way to build a glossary with atom,  I think that would be a good feature.

**Comment by yitzchak** [comment] 2016-09-09 13:27
Thank you for the feature request! This looks like a duplicate of #179. I am going to close the issue, but please feel free to follow/contribute to any discussion there.

If you use `latexmk` it may be possible to integrate glossary building directly into its build process as discussed in [How to make Latexmk use makeglossaries?](http://tex.stackexchange.com/questions/1226/how-to-make-latexmk-use-makeglossaries). I am not sure if those methods still work as I am not an expert on `makeglossaries`.

**Closed by yitzchak** 2016-09-09 13:27 UTC
Labels: enhancement
