### ISSUE TITLE
Failed to activate

### ISSUE THREAD

**Issue by Evpok** [thomasjo/atom-latex#488] opened 2018-09-27 11:19 UTC
Exception thrown at package activation

**Atom**: 1.32.0-beta0 x64
**Electron**: 2.0.9
**OS**: KDE neon
**Thrown From**: [latex](https://github.com/thomasjo/atom-latex) package 0.50.0

### Stack Trace

Failed to activate the latex package

```
At Class constructor Disposable cannot be invoked without 'new'

TypeError: Class constructor Disposable cannot be invoked without 'new'
    at /packages/latex/lib/latex.js:18:27)
    at Object.bootstrap (/packages/latex/lib/main.js:85:20)
    at Object.activate (/packages/latex/lib/main.js:7:10)
    at Package.activateNow (/usr/share/atom-beta/resources/app/static/<embedded>:11:2898797)
    at string.e.trim.length.activationHookSubscriptions.add.packageManager.onDidTriggerActivationHook (/usr/share/atom-beta/resources/app/static/<embedded>:14:2445)
    at Function.simpleDispatch (/usr/share/atom-beta/resources/app/static/<embedded>:11:1183960)
    at Emitter.emit (/usr/share/atom-beta/resources/app/static/<embedded>:11:1185149)
    at PackageManager.triggerDeferredActivationHooks (/usr/share/atom-beta/resources/app/static/<embedded>:11:378885)
    at Promise.all.then (/usr/share/atom-beta/resources/app/static/<embedded>:11:377683)
    at <anonymous>
```

**Comment by Aerijo** [comment] 2018-09-28 10:45
I think it's a babel thing; see [this issue](https://github.com/babel/babel/issues/7022). Not sure what caused it yet, or if it can be fixed on this end.

**Comment by Aerijo** [comment] 2018-09-28 12:46
Wow, it's obscure.

So this package transpiles eveything through babel, and targets es2015 or something. That's fine. I spent a long time looking for changes in Babel related files in Atom core, but no dice. Then I search the error some more, and see [a passing comment](https://github.com/meteor/meteor/issues/9934#issuecomment-406888390) about this being incompatible with es6 modules. 

OK. So the issue is we're extending `Disposable`, which is defined in `event-kit`. Turns out that module was decaffeinated a couple of weeks ago, into the new es6 syntax. Before this, it was being compiled into the same JS version as Babel is, so everything was happy. Now it's not.

**Comment by thomasjo** [comment] 2018-10-08 13:00
@Aerijo Thanks for tracking down the problem! Now to figure out if there's some way of fixing this without making changes to event-kit...

**Comment by delta-one** [comment] 2018-10-12 11:12
I also get the same error with Atom 1.31.2, but my stack trace is different, so it's likely not the sam eissue.

**Atom**: 1.31.2 x64
**Electron**: 2.0.7
**OS**: Debian GNU/Linux
**Thrown From**: [latex](https://github.com/thomasjo/atom-latex) package 0.50.0


### Stack Trace

Failed to activate the latex package

```
At Cannot find module '../type/js/undefined'

Error: Cannot find module '../type/js/undefined'
    at Module._resolveFilename (module.js:543:15)
    at Module._resolveFilename (/usr/share/atom/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (/usr/share/atom/resources/app/src/module-cache.js:354:58)
    at Module.require (/app.asar/static/index.js:40:43)
    at require (/usr/share/atom/resources/app/src/native-compile-cache.js:66:33)
    at /packages/latex/node_modules/js-yaml/lib/js-yaml/schema/default_full.js:21:5)
    at /packages/latex/node_modules/js-yaml/lib/js-yaml/schema/default_full.js:27:3)
    at Module.get_Module._compile (/usr/share/atom/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (/usr/share/atom/resources/app/src/compile-cache.js:240:29)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (/usr/share/atom/resources/app/src/native-compile-cache.js:66:33)
    at /packages/latex/node_modules/js-yaml/lib/js-yaml/loader.js:9:27)
    at /packages/latex/node_modules/js-yaml/lib/js-yaml/loader.js:1600:3)
    at Module.get_Module._compile (/usr/share/atom/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (/usr/share/atom/resources/app/src/compile-cache.js:240:29)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (/usr/share/atom/resources/app/src/native-compile-cache.js:66:33)
    at /packages/latex/node_modules/js-yaml/lib/js-yaml.js:4:14)
    at /packages/latex/node_modules/js-yaml/lib/js-yaml.js:41:3)
    at Module.get_Module._compile (/usr/share/atom/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (/usr/share/atom/resources/app/src/compile-cache.js:240:29)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
```

**Comment by maxbrunsfeld** [comment] 2018-10-23 03:17
Wow, sorry this was broken for so long. The bug was a very unexpected consequence of using JavaScript classes, instead of Coffee-script classes (which compile to regular JavaScript functions). This will be fixed in Atom 1.32.

**Comment by thomasjo** [comment] 2018-10-23 06:50
@maxbrunsfeld Thanks for the fix and the update!

**Comment by thomasjo** [comment] 2018-10-23 06:53
Closing this as fixed; the issue will not be present when Atom 1.32 is released.

**Closed by thomasjo** 2018-10-23 06:53 UTC
Labels: bug
