### ISSUE TITLE
outputFilePath

### ISSUE THREAD

**Issue by Sasha4ever** [thomasjo/atom-latex#37] opened 2014-11-11 15:01 UTC
MAC OS
after build
Uncaught TypeError: Cannot read property 'outputFilePath' of undefined

**Comment by OtoriTakeo** [comment] 2015-01-06 08:50
Same here:

## Stack Trace 

/Users/NAME/.atom/packages/latex/lib/latex.coffee:63

TypeError: Cannot read property 'outputFilePath' of undefined
  at /Users/NAME/.atom/packages/latex/lib/latex.coffee:63:24
  at /Users/NAME/.atom/packages/latex/lib/builders/latexmk.coffee:17:9
  at ChildProcess.exithandler (child_process.js:752:5)
  at ChildProcess.emit (events.js:110:17)
  at maybeClose (child_process.js:1013:16)
  at Process.ChildProcess._handle.onexit (child_process.js:1085:5)

My system:
**Atom Version**: 0.166.0
**System**: Mac OS X 10.10.1
**Thrown From**: [latex](https://github.com/thomasjo/atom-latex) package, v0.14.0

Neither Dragynfyre nor aclemen1 suggestions helped. TeX distribution is in its default location `/usr/texbin`, although i did not install the GUI Tools.
I recently updated Tex by using `sudo tlmgr update --all`, maybe this caused the error/bug.

**Comment by hortelano** [comment] 2015-01-10 19:05
I have the same problem on both platforms: Mac OS X 10.10.1 and Ubuntu 14.04.1 LTS. Atom has been tested with fresh installations of the system and MacTeX on Mac OS X and texlive metapackage in Ubuntu. I installed the system, then MacTeX or texlive, then Atom, then language-latex and latex packages of Atom; Ctrl + Alt + B and then  the message that appears on the photos appears
![image_mac_os_x_10 101](https://cloud.githubusercontent.com/assets/10478710/5692780/025a1e8e-9904-11e4-862f-62da1c061e0e.png)
![image_ubuntu_10 4 1_lts](https://cloud.githubusercontent.com/assets/10478710/5692781/0728cc30-9904-11e4-874f-a72559d934db.png)

:

**Comment by Koltharius** [comment] 2015-01-10 19:19
Same error 

At /home/david/.atom/packages/latex/lib/latex.coffee:63

TypeError: Cannot read property 'outputFilePath' of undefined
at /home/david/.atom/packages/latex/lib/latex.coffee:63:24
at /home/david/.atom/packages/latex/lib/builders/latexmk.coffee:17:9
at ChildProcess.exithandler (child_process.js:752:5)
at ChildProcess.emit (events.js:110:17)
at maybeClose (child_process.js:1013:16)
at Socket. (child_process.js:1181:11)
at Socket.emit (events.js:107:17)
at Pipe.close (net.js:461:12)

My system:
Atom Version: 0.169.0
System: Manjaro Linux 64-bit with Gnome version 3.14.2
Thrown From: latex package, v0.14.0

**Comment by OtoriTakeo** [comment] 2015-01-16 11:38
Found a solution. I had to update all *Tex-Packages. Seems like there was/is an error in one of the used packages.
Just enter the following commands.
`tlmgr update --all`
`tlmgr update --self`

It could be necessary to update some packages manually by using the following commands.
`tlmgr update --list`
`tlmgr update PACKAGE`

Make sure you are administrator, `sudo su` worked fine for me - i needed to go through the steps three times to have all packages up to date.

**Comment by ELD** [comment] 2015-01-16 14:32
How strange, that totally worked for me. Thanks, @OtoriTakeo!

**Comment by hortelano** [comment] 2015-01-16 21:22
The update for texlive packages this morning has solved the problem on my mac  ... but the problem persists in my Ubuntu.

**Comment by hortelano** [comment] 2015-02-01 17:59
A LaTeX installation following the instricciones explained in
                http://ubuntudriver.blogspot.com.es/2015/01/instalar-tex-live-en-ubuntu-sin-usar.html
 and subsequent installation of Atom solves the problem in Ubuntu LTS 14.04.01.

**Comment by thomasjo** [comment] 2015-02-06 10:53
This should now be fixed in v0.18.0. Although it does not resolve the underlying issue which is usually caused by an incorrect `texPath` setting. The package default is seemingly empty, but an empty value means it tries to resolve a [default based on your operating system](https://github.com/thomasjo/atom-latex/blob/1c26759efbbe332ddc20cfa32cbdd5d3779b09f3/lib/builder.coffee#L25:L30).

**Closed** 2015-03-02 14:31 UTC
Labels: more-information-needed
