### ISSUE TITLE
An error occurred while trying to run opener(1)

### ISSUE THREAD

**Issue by eratio08** [thomasjo/atom-latex#269] opened 2016-10-19 08:30 UTC
After successfully building a project I get this error.

`An error occurred while trying to run opener(1)`

I'm on a macOS 10.12 using MacTeX 2016 and Skim 1.4.22, Atom 1.11.2

The built document opens and sync seems to work fine.
Can't see any error.
Just wanted to report this, seems like no one else have had this before.

**Comment by thomasjo** [comment] 2016-10-19 08:58
This is caused by a [bug in Skim](https://sourceforge.net/p/skim-app/bugs/1128/), and will supposedly be fixed in the next release.

**Comment by eratio08** [comment] 2016-10-19 08:58
ok 😃  thanks!

**Closed by thomasjo** 2016-10-19 08:58 UTC

**Comment by thomasjo** [comment] 2016-10-19 09:00
You're welcome! Thanks for reporting the issue 🙇
