### ISSUE TITLE
Error when PDF viewer is already open

### ISSUE THREAD

**Issue by justinriddoch** [thomasjo/atom-latex#252] opened 2016-10-11 18:24 UTC
If I build my latex file with my PDF viewer (SumatraPDF) already open then I get the following error "An error occurred while trying to run opener (1)." When the error is displayed it doesn't show errors or warnings from the latex log file. The PDF file is created and updated in Sumatra and the window does become selected. If I turn off the option "Open result after successful build" or close Sumatra before building then I no longer get the error and can see the warnings from the Latex log file.

**Comment by yitzchak** [comment] 2016-10-11 19:02
Thank for the issue report! 

Unfortunately there is no way for us to detect and close SumatraPDF unless we resort to DDE as detailed in #119. At this point we are not planning on adding such a feature because of significant implementation issues.

**Comment by justinriddoch** [comment] 2016-10-13 14:25
This is a new issue for me, I used atom with Sumatra with no issue for more than a year. It happened after updating atom-latex and switching over to latexmk.

**Comment by justinriddoch** [comment] 2016-10-18 17:08
After updating atom and atom-latex on my Mac, I get the same error. However I now get the error even if Skim is closed. If I use pdf-view then there is no error. I wouldn't mind the error so much if it did not overriding the latex warnings, as it doesn't seem to be effecting the build/opening of the PDF. To that end I commented out line 16 in /lib/opener.js and everything seems to be running smoothly. Would it be possible to append the error message to the latex log file instead of overriding it at the bottom of the screen?

**Comment by yitzchak** [comment] 2016-10-18 17:10
The Skim error is a bug in their SyncTeX. Is has been reported and will fixed in the next version.

**Comment by justinriddoch** [comment] 2016-10-18 17:11
So are the Sumatra and Skim errors totally unrelated even though the error message is the same? Or is it possible the Sumatra error is related SyncTex as well?

**Comment by yitzchak** [comment] 2016-10-18 17:13
They are probably unrelated. I'll have to get on Windows machine to see if I can reproduce the Sumatra issue at some point.

**Comment by yitzchak** [comment] 2016-10-18 17:14
But even if I can, we probably won't be able to do much about it since in the past the obstacle has been Sumatra's insistence on DDE messages.

**Comment by yitzchak** [comment] 2016-10-19 10:45
I just reproduced this.

**Closed** 2016-10-23 15:44 UTC
