### ISSUE TITLE
custom build options

### ISSUE THREAD

**Issue by justinriddoch** [thomasjo/atom-latex#182] opened 2016-05-30 18:38 UTC
I often have to build my latex document twice in order to get a successful output, the first build takes a while but always reports an error, if I build immediately afterwards there is no error and the output opens instantly. It would be helpful to have an option to build twice when pressing ctrl-alt-b once. 

Note: I am not entirely sure, but I think I have to build twice because the first build looks for labels/references and bib items and the second build adds these references etc. to the output.

**Comment by thomasjo** [comment] 2016-06-14 10:39
Your description makes it sounds as if there's a hidden problem with e.g. your bibliography that is not being caught properly in the (extremely naive) log parsing we're doing. But since a second build seems to work, it could also simply be that the build does finish successfully—meaning it produces the expected output—but `latexmk` is reporting an exit code that is being treated as an error.

Both `latexmk` and `texify` will run multiple builds in order to generate bibliography, nomenclature, etc. So there should be no need to introduce further build customizations for this.

Are you able to provide me with a minimal example that reproduces the problem?

**Comment by yitzchak** [comment] 2016-09-15 18:30
Closing due to inability to reproduce. Will reopen if needed.

**Closed by yitzchak** 2016-09-15 18:30 UTC
Labels: needs info, needs reproduction

**Comment by GillesC** [comment] 2017-06-23 08:18
Hello

It seems that I have the same problem.
Information:
- engine : lualatex
- tex distro: miktex
- os: windows 10

This issue occured after I changed from pdflatex to lualatex to support fontspec (I think). Now I first get an error message from latexmk  ("`Failure in some part of making files.`"). After compiling again, the problem seems to be resolved.

**Comment by matthiaschung** [comment] 2017-12-27 15:30
Hi,

I have the same problem on my Mac: "latexmk: Failure in some part of making files". A second run will not create an error. Mac, High Sierra, MacTex, running pdflatex.

**Comment by LinxiFan** [comment] 2018-06-07 06:36
Resurfacing the issue: I have the same problem. Mac, Sierra, latexmk, pdflatex

**Comment by Liskie** [comment] 2019-01-28 16:31
I have the same problem on my Mac, although a second build returns no error, the output remains unchanged even if I've edited several places.
![image](https://user-images.githubusercontent.com/31062113/51850660-25864d00-235d-11e9-9140-d52e50cfb701.png)

**Comment by EthanReese** [comment] 2021-01-31 22:21
I have the same error on my M1 Mac running Big Sur: "latexmk: Failure in some part of making files". A second run removes this error and opens a pdf preview as expected. This is reproduced by compiling all files, even a basic test document with only one line of text.

engine: pdflatex
tex distro: mactex
OS: macOS 11.1
