### ISSUE TITLE
ctrl+alt+b does nothing

### ISSUE THREAD

**Issue by TheChymera** [thomasjo/atom-latex#71] opened 2015-04-04 15:16 UTC
Hi, I installed the package and tried the keybinding out. It does not do anything as far a I can tell. I tried pressing either alt and ctrl key, but still nothing. Can you help me out?

**Comment by thomasjo** [comment] 2015-04-05 10:51
First of all, let's make sure the keybinding works; open the *Key Binding Resolver* (from the command palette or with e.g. <kbd>cmd</kbd> + <kbd>.</kbd>), them press <kbd>ctrl</kbd> + <kbd>alt</kbd> + <kbd>b</kbd>. You should hopefully see `latex:build` at the top of the list. Feel free to add a screenshot.

Assuming the keybinding works correctly, be aware that the *Build* command only executes on TeX files which right now is determined by extension — `.tex` (and `.lhs`). In other words, the *Build* command is meant to be executed from within an active editor for a `.tex` file.

If the keybind works, and you are are executing the command from a `.tex` file and nothing is happening, please provide some more details about your version of Atom, OS, TeX distribution etc.

**Comment by TheChymera** [comment] 2015-04-05 11:45
Ah, perhaps it does work, and I just missed the latex compilation error at the bottom (now opened in a side pane).

Using `atom-0.184.0` and `atom-latex-0.19.1`.

![screenshot from 2015-04-05 13 42 41](https://cloud.githubusercontent.com/assets/950524/6996735/f9daaffc-db99-11e4-9f76-cd1bf373d136.png)

**Comment by thomasjo** [comment] 2015-04-05 12:27
Unfortunately the error story in atom-latex is still really bad — the error you're seeing comes directly from `latexmk`. A quick Google search led me to this, which seems to be relevant:
http://tex.stackexchange.com/questions/83101/option-clash-for-package-xcolor

Since this error is not actually caused by atom-latex, I'm going to close this issue.

**Comment by TheChymera** [comment] 2015-04-05 13:21
ok, I solved that issue, but now I get another error:

```
LaTeX errors
/home/chymera/.atom/packages/latex/lib/loggers/console-logger.coffee:25 TeXification failed with status code 12
```

In the side bar. I'm pretty sure this is not a latex error, since building the source with `pdflatex` from my terminal works.

**Comment by Victorystick** [comment] 2015-05-17 10:22
Any progress on this? Have been getting these errors for a while?

```
LaTeX errors
/home/victorystick/.atom/packages/latex/lib/loggers/console-logger.js:74 TeXification failed with status code 12
index.js:9 Unhandled promise rejection with error: 12
```

**Comment by thomasjo** [comment] 2015-05-17 12:15
@Victorystick Any chance you can reproduce this with a simple file, and share the log file with us via a Gist (or similar)?

**Comment by Victorystick** [comment] 2015-05-17 13:14
Hmm... After a few restarts it appears to work. Never mind.

**Comment by TheChymera** [comment] 2015-05-17 15:30
same here, no more errors (ATM)

**Comment by rcompton** [comment] 2015-05-23 00:19
@TheChymera I just installed and, as far as I can tell, this package does nothing. What did you do to get that sidepane to appear? I'm on Ubuntu 14.04 with texlive and a working latexmk command

**Comment by TheChymera** [comment] 2015-05-23 04:55
@rcompton I clicked the little error/warning message in the lower right of the screen.

**Comment by thomasjo** [comment] 2015-05-24 09:46
@rcompton If you update the package to v0.24.0 (latest version as of right now), when an error occurs, simply click on the "LaTeX compilation error" indicator in the status bar and it will open the log file produced by `latexmk`.

If clicking that doesn't do anything, the most likely issue is that the default `texPath` assumed in the package for Unix-like systems (`/usr/texbin`) is not correct for your system. That error is (or at least should be) reported in Atom's developer console. To fix the problem, simply open the settings view for this package and change the *TeX Path* option to point to the correct path.

Sorry about the trouble! I'm hoping to improve the initial installation experience with #64.

**Comment by aeniwon** [comment] 2015-06-11 22:18
Hi, I haven't used latex/atom for while and today when I opened I updated so had new version of atom/latex plugin. compiling any latex documents give me the error as showed in picture. Which is similar to OP issue. Running same latex code worked in Sublime text, so I don't think it is because of bad code. Do you know how I can fix it? Thanks
![screenshot 2015-06-12 00 16 30](https://cloud.githubusercontent.com/assets/7695776/8119756/5376a286-1098-11e5-9d06-d050f2de0924.png)

**Comment by thomasjo** [comment] 2015-06-21 14:26
Since I've not had any more response on this, I'm going to assume the underlying problem is resolved. Re-open (or let me know) if that's not the case.

**Closed by thomasjo** 2015-06-21 14:26 UTC
Labels: more-information-needed, needs-reproduction

**Comment by menzenski** [comment] 2015-07-14 23:02
Hi, I think I'm having a similar issue as TheChymera; I hope you don't mind me commenting here rather than opening a new issue. It may very well be an error on my end.

I've got a very simple `.tex` file (which compiles just fine for me in emacs/Aquamacs):

```latex
\documentclass{article}
\begin{document}
This is my document!
\end{document}
```

The keybinding <kbd>ctrl</kbd>+<kbd>alt</kbd>+<kbd>b</kbd> works. The message "Compiling TeX file" flashes briefly when I enter it, and is then replaced by "LaTeX compilation error". Clicking this does nothing (unless I've typeset this document with Aquamacs, and then I can see the existing `.log` file—there's no new `.log` file created).

> If the keybind works, and you are are executing the command from a .tex file and nothing is happening, please provide some more details about your version of Atom, OS, TeX distribution etc.

I am using `atom 1.0.2` and `atom-latex 0.25.0` on Mac OS X 10.10.3. `$ latex --version` returns `pdfTeX 3.1415926-1.40.11-2.2 (TeX Live 2010)` (first line only) and `$ latexmk --version` returns `Latexmk, John Collins, 18 May 2010. Version 4.16a`.

**Comment by thomasjo** [comment] 2015-07-15 12:58
@menzenski I see that you're using an older distribution of MacTeX (TeX Live). This is most likely an issue related to the `PATH` environment variable. Since this is only "inherited" by Atom if it's launched from e.g. Terminal you should try changing the `latex.texPath` configuration option, and set it to the directory containing your copy of `latexmk`. If you're unsure where that is, try executing `which latexmk` from a terminal and it should give you the full path to `latexmk`, so simply grab the full path to its parent directory and use that for `latex.texPath`.

<img width="719" alt="settings_-__users_thomasjo_-_atom" src="https://cloud.githubusercontent.com/assets/3622/8698904/d9086168-2b01-11e5-8f55-0a9b38e1e125.png">

**Comment by menzenski** [comment] 2015-09-22 22:56
@thomasjo After putting it off for as long as possible, I've finally bitten the bullet and upgraded from TeX Live 2010 to TeX Live 2015. With `/Library/TeX/texbin/` in the TeX Path field in settings, everything works just fine: my XeTeX documents compile successfully in Atom with <kbd>ctrl</kbd>+<kbd>alt</kbd>+<kbd>b</kbd>. Many (belated) thanks for your helpful response.

**Comment by thedataking** [comment] 2015-11-29 23:30
I believe I have the same issue. TeXifying with pdflatex from the command line returns status code 0. TeXifying using your (otherwise fantastic) plug-in, gives me the same error mentioned by the previous posters: 
``LaTeX errors`` in console-logger.js:8
``TeXificiation failed with status code 12`` in console-logger.js:26
``Uncaught (in promise)``

Again, my code build's cleanly. I'm linking to my log file 
[firepaper.log.txt](https://github.com/thomasjo/atom-latex/files/46795/firepaper.log.txt) in case that helps. (I had to append .txt to make GitHub happy.) Also, re-TeXifying without changing the document succeeds without the any errors being shown in Atom.

Thanks again for all your hard work which I benefit from every day!

Best,
Per

**Comment by loveingvera** [comment] 2016-08-07 09:46
With TeX Live 2014 on Mac, the "Tex Path" is like "/Library/Tex/Distributions/Programs/texbin". :)

**Comment by tranquillemartin** [comment] 2016-10-21 14:38
Bonjour,

I have just have a similar issue on Windows. I worked with sublime text and TeX Live 2014 and I have tried to use Atom with atom-latex but even with good settings running build command was impossible.

Now, I have updated TeX Live to 2016 and now everything works.

Camille
