### ISSUE TITLE
Project management

### ISSUE THREAD

**Issue by boborbt** [thomasjo/atom-latex#14] opened 2014-07-11 12:22 UTC
There should be a way to specify options for a particular latex project. It could be a JSON file to be save din the project directory or something similar. 

Options to be included:
- setting the latex master file: it is need to allow the editor to know which file needs to be compiled when there exists more than one .tex file in the current directory;
- output directory: this should override the global package setting;
- building tool: to allow specifying which building tool to be used (never personally had problems with the  one currently used, but I assume that it *may* be a useful option).

I'm going to submit a pull request that updates the TODO list according to the points suggested here.

**Comment by skogshjort** [comment] 2015-09-22 15:06
Setting a master document would be very convenient, I usually divide my papers up in parts, and accidently compile a part of the paper because I didn't navigate back to the master document before building.. So what's the status of this?

**Comment by thomasjo** [comment] 2015-09-23 18:53
@skogshjort master file concept is possible via the magic comment/directive `!TEX root` (see e.g. http://tex.stackexchange.com/questions/78101/when-and-why-should-i-use-tex-ts-program-and-tex-encoding)

**Comment by jeremy-y12** [comment] 2015-12-10 18:05
Regarding the master latex file issue, I like the solution used by the vimlatex plugin (especially the recursive search feature). I am reproducing here part of [the manual](https://github.com/lervag/vimtex/blob/master/doc/vimtex.txt) for reference:

>vimtex supports most multi-file documents.  It uses a recursive search
>algorithm that should find the main LaTeX file in most cases.  For special
>cases, there are several alternative methods for specifying the main file, see
>below.  Note that the priority of the following methods are as follows:
>
>  1. Buffer variable
>  2. TeX root specifier
>  3. Subfiles package
>  4. File `.latexmain` specifier
>  5. Recursive search
>
>Recursive search
>  The recursive search detects the main LaTeX file by searching for a file in
>  the current and parent directories that includes the present file and that
>  has the `\documentclass` line.
>
>  This should work in most cases, but it may fail if for instance the project
>  structure is something like this:
>
>    path1/main.tex
>    path2/chapter.tex
>
>  That is, the main file detection will not work for the file `chapter.tex`,
>  because the main file does not live in the same folder or a parent folder.

**Comment by yitzchak** [comment] 2016-09-09 16:26
Closing since we have magic comment support for `root`, `program`, and `builder`.

**Closed by yitzchak** 2016-09-09 16:26 UTC
Labels: enhancement, feature

**Comment by joergweber** [comment] 2017-02-20 11:13
I know how to use magic comments to set a master file, but there is a good reason to potentially add support for a main file specifier through an external file (e.g. '.latexmain'): collaborators may use other editors that require their own magic comments (or the regularly remove my magic comments...).

Would you ever consider adding support for this? Some other packages (e.g. [atom-latex](https://github.com/James-Yu/Atom-LaTeX)) have support for this, but I find that your package works best for me.

**Comment by thomasjo** [comment] 2017-02-20 11:17
@joergweber This is already supported (https://github.com/thomasjo/atom-latex/pull/312), thanks to @yitzchak

**Comment by joergweber** [comment] 2017-02-20 11:28
Ah, thanks! Why did I not see that...

**Comment by joergweber** [comment] 2017-02-20 11:38
Perhaps I misunderstand something here, but the documentation states: "Specify the root file that should be built. _Only available via "magic" TeX comments._"

So I don't think what am after is supported...?

**Comment by thomasjo** [comment] 2017-02-20 11:48
Sorry, you're correct. I was a bit too quick on the trigger. Exactly what you want, moving `root` magic comments out of the child documents, to some type of project-level configuration file, is not currently supported.

We haven't found any equally good alternatives to the current approach, which doesn't have any downsides. If someone can propose an equally good approach with zero side-effects, we're happy to merge an implementation.
