### ISSUE TITLE
"latex compilation error" after atom 1.7.x update

### ISSUE THREAD

**Issue by chenyuewu** [thomasjo/atom-latex#180] opened 2016-04-21 20:51 UTC
On Windows 10, with atom 1.7.2.
Same tex file can be compiled outside of atom and previous in atom 1.6.2.
If I build a tex file with miktex and do not clean the directory. The tex file can be compiled in atom without error message. But the corresponding pdf file will not be updated even if the tex file is modified. And if the .log file is deleted, compilation in atom is broken again with error message latex compilation error.

**Comment by chenyuewu** [comment] 2016-04-21 21:09
If I build a tex file with miktex and do not clean the directory. The tex file can be compiled in atom without error message. But the corresponding pdf file will not be updated even if  the tex file is modified. And if the `.log` file is deleted, compilation in atom is broken again with error message `latex compilation error`.

**Comment by emazomenos** [comment] 2016-05-16 13:57
Hi all, 
I verify the above behavior in Windows 10 - Atom 1.7.3 (latex package 0.32.0). No settings altered, compilation (Ctr-Alt B) does not appear to work.

**Comment by thomasjo** [comment] 2016-05-18 14:08
@chenyuewu What version of MiKTeX are you using?

**Comment by emazomenos** [comment] 2016-05-18 14:34
Hi Thomas, sorry about forgetting that at. I am using Miktex 2.9 in Win 10 64bit. I am using Miktex 2.9 for a few months now and it was working just fine with Atom up to a few weeks ago. The behaviour i am experiencing is the same with @chenyuewu.

**Comment by chenyuewu** [comment] 2016-05-21 20:05
@thomasjo It's Miktex 2.9 and version of pdflatex is 3.14159265-2.6-1.40.16.

**Comment by uomoinverde** [comment] 2016-08-23 15:50
I got this on my system also. The `build` command seemed to work at first, but after the first time both pressing the menu option and the keyboard shortcut didn't trigger the build action anymore. Same for `clean`.

How can I help? Which information is required?

### Some info
+ Operating system: Ubuntu 16.04 TLS
+ Atom version: 1.9.0
+ builder: latexmk 4.44
+ engine: *pdflatex* pdfTeX 3.14159265-2.6-1.40.16 (TeX Live 2015)

**Comment by timofeymukha** [comment] 2016-08-30 14:19
What I have seems to be similar.
The build command woks once, but gives "Latex compolation error" on succesive attempts. If I clean, then I can build again.

I am on Windows 10 + Atom 1.9.9

**Comment by thomasjo** [comment] 2016-08-30 14:22
I'm unable to reproduce this. It would be really helpful if one (or all) of you could provide a *minimal example* that reliably reproduces the problem.

**Comment by DblAAssassin** [comment] 2016-08-31 00:28
I am using Atom 1.9.9 on Windows 10 64-bit, and latex 0.35.1 and getting the same error, with this sample of code.

```
\documentclass[12pt]{article}
\author{DblAAssassin}
\title{Sample}

\begin{document}
\maketitle

\begin{abstract}
This is an abstract
\end{abstract}

\end{document}
```

**Comment by yitzchak** [comment] 2016-10-05 14:40
We just released v0.37.0 which has some significant changes to the build process including visual display of errors. If you have seen the bug reported in this issue please upgrade. Let us know this bug still exists or if it has been resolved.

**Comment by DblAAssassin** [comment] 2016-10-08 23:16
I am getting the error
`TeXification failed with status code 1`
Is this a problem with my teX distribution install?

**Comment by yitzchak** [comment] 2016-10-08 23:33
@DblAAssassin Are you using `texify` or `latexmk`?

**Comment by DblAAssassin** [comment] 2016-10-09 16:49
@yitzchak I am using texlive

**Comment by yitzchak** [comment] 2016-10-09 16:51
Run `latexmk -v` from the command line to see what version you have. Then try running `latexmk -pdf foo.tex` from the command line, where `foo.tex` is the name of your LaTeX file.

**Comment by yitzchak** [comment] 2016-10-18 22:52
Closing due to lack of reproduction/information. Will reopen if needed.

**Closed by yitzchak** 2016-10-18 22:52 UTC
Labels: bug, needs info, needs reproduction
