### ISSUE TITLE
Deprecated selector in `latex\styles\markers.atom-text-editor.less`

### ISSUE THREAD

**Issue by thibferr76** [thomasjo/atom-latex#320] opened 2016-12-25 12:03 UTC
In `latex\styles\markers.atom-text-editor.less`: 

Starting from Atom v1.13.0, the contents of `atom-text-editor` elements are no longer encapsulated within a shadow DOM boundary. This means you should stop using `:host` and `::shadow` pseudo-selectors, and prepend all your syntax selectors with `syntax--`. To prevent breakage with existing style sheets, Atom will automatically upgrade the following selectors:

* `:host(:host) .gutter .line-number.latex-error` => `atom-text-editor .gutter .line-number.latex-error`

* `:host(:host) .gutter .line-number.latex-warning` => `atom-text-editor .gutter .line-number.latex-warning`

* `:host(:host) .gutter .line-number.latex-info` => `atom-text-editor .gutter .line-number.latex-info`

Automatic translation of selectors will be removed in a few release cycles to minimize startup time. Please, make sure to upgrade the above selectors as soon as possible.

**Comment by yitzchak** [comment] 2016-12-25 12:12
Thanks for reporting the issue.

We have a PR (#267) that will resolve once v0.13.0 is out of beta.

Closing this since it is a duplicate of of #319.

**Closed by yitzchak** 2016-12-25 12:12 UTC
