### ISSUE TITLE
Weird behaviour when latexmk not installed

### ISSUE THREAD

**Issue by galgalesh** [thomasjo/atom-latex#115] opened 2015-08-28 09:00 UTC
# Steps to reproduce:

Compile latex project in atom using atom-latex without latexmk installed.

# Expected behaviour:

Error explaining latexmk has to be installed

# Behaviour you get:

 A generic error message when you click on that message either one of two things happen:

- When an old log [from other program] exists: The old log opens. Very confusing because old log states compiling succeeded
- Without old log: nothing happens.

Related: #62

**Comment by thomasjo** [comment] 2015-08-28 19:23
I agree. The current behavior is far from ideal. Since this issue is essentially a duplicate of #54, I'm going to close this, but thanks reporting this with such great detail—much appreciated :bow:

**Closed by thomasjo** 2015-08-28 19:23 UTC

**Comment by thomasjo** [comment] 2015-08-28 19:24
I'm close on landing #64 by the way. Just need to find some time to find a sensible way to detect "initial launch" of the package to handle to showing the guide after a user has installed the package.
