### ISSUE TITLE
Biblatex issue

### ISSUE THREAD

**Issue by zvtoth** [thomasjo/atom-latex#178] opened 2016-04-08 17:14 UTC
I did not have this issue with the previous version, but here is a problem: I get a compilation error whenever I try to include a bibliography file. 
I use TexLive2014, on Mac OSX, biblatex with Biber as backend (in the PATH). 

For a test I had a basic article with a bib file referenced in the same folder. 
The pdf is generated, so is the .aux and .bcf, but the .bbl file isn't, which might be the source of the overall error. (And indeed, the references do not show up in the compiled pdf.)

Any idea about this?

**Comment by thomasjo** [comment] 2016-04-08 17:21
Can you provide me with a minimal example that reproduces the problem? I'm working on large documents all day long, and I've not had any problems with this, so I'll need an example that causes problems on your system to see if I can reproduce it on mine.

Thanks!

**Comment by mockham** [comment] 2016-04-08 17:24
Here is a repo with all the files generated:
https://github.com/mockham/Biblatex-trial.git

**Comment by nomoon** [comment] 2016-04-13 20:40
I have a similar problem so long as I haven't cited anything. Latex warns its usual "The bibliography is empty" (which is fine) and the PDF generates in the build folder, but the package shows "compilation error" and doesn't move the PDF to the root folder or spawn the viewer.

**Comment by zvtoth** [comment] 2016-04-28 19:45
I have been experimenting with this since, but the problem is still the same. If I compile the tex with another editor, delete the output files except the .bbl, then run it in Atom, the output is fine. But it seems that somehow I can't generate the .bbl, and if there isn't one (or if it's old and some new references have been added), then I get the error.

**Comment by thomasjo** [comment] 2016-04-29 08:07
@zvtoth I have unfortunately been unable to reproduce this. Does it work if you execute `latexmk` directly from a terminal? Need to narrow down the possibly causes, and I was thinking we could start by seeing if this is somehow caused by an "invalid" environment within Atom.

**Comment by zvtoth** [comment] 2016-05-29 16:16
Thanks Thomas, and sorry for the late response. It might have been a problem with my Tex distribution; I just reinstalled the whole thing (Tex 2015; I had an earlier one anyway), and it seems to work now. (It was a little strange, because it did *not* work from the terminal, even though it did in Texpad, which is another program I used to use to compile.) Anyway, thank you for your help, I think this can be closed now.

**Comment by thomasjo** [comment] 2016-06-01 16:03
Since it seems like this issue has been resolved, I'm going to close this for now. Feel free to re-open if you manage to reproduce.

**Closed by thomasjo** 2016-06-01 16:03 UTC
Labels: more information needed, needs reproduction

**Comment by ptitjes** [comment] 2016-10-12 10:42
Hi,

I can reproduce the problem. It seems to come from the absolute `-outdir` argument given to `latexmk` which is problematic security-wise. See the `-outdir` documentation in the manpage of `latexmk` that explains it all.

For instance, running the following command (that produces the `latex` Atom plugin) fails when launched from the terminal:
```
latexmk -interaction=nonstopmode -f -cd -file-line-error -shell-escape -synctex=1 -pdf -outdir="/home/didier/Documents/Work/Doctorat/Publications/k-sequentiality/seq-transducers/fossacs/.build" "/home/didier/Documents/Work/Doctorat/Publications/k-sequentiality/seq-transducers/fossacs/main.tex"
```

Whereas the following one succeeds:
```
latexmk -interaction=nonstopmode -f -cd -file-line-error -shell-escape -synctex=1 -pdf -outdir=".build" "main.tex"
```

From the information, in the manpage of `latexmk` it says that you can add an environment variable (`openout_any=a`) to control the security behaviour.

So I just modified the line 18 of `latexmk.js` to:
```
    const command = `env openout_any=a ${this.executable} ${args.join(' ')}`
```
And now it works correctly.

Ask if you need any more information!

**Comment by yitzchak** [comment] 2016-10-12 12:10
Thanks @ptitjes! This looks like #104. I'll see if I use your discoveries to solve that issue.

Cheers!

**Comment by ptitjes** [comment] 2016-10-12 12:52
@yitzchak Indeed ! I had not seen this issue. Sorry for the noise :)

**Comment by yitzchak** [comment] 2016-10-12 13:13
No worries!
