### ISSUE TITLE
Support for (u)pLaTeX

### ISSUE THREAD

**Issue by yudai-nkt** [thomasjo/atom-latex#220] opened 2016-09-12 07:38 UTC
I'm happy to see this package being actively updated recently and I think this is a good time to ask for a new feature.

As pdfTeX, XeTeX and LuaTeX do not have enough capability of Japanese typesetting without appropriate packages (e.g., [`zxjatype`](https://www.ctan.org/pkg/zxjatype) and [`luatex-ja`](https://www.ctan.org/pkg/luatexja)), the most prevailing method of Japanese LaTeX document is to use (u)pLaTeX and DVI driver (mainly dvipdfmx).

The current `latex` package can already interpret the magic comment like `% !TEX program = uplatex` to some extent, but also has some problems. Let me consider the following file `foo.tex`.

```latex
% !TEX program = uplatex
\documentclass[uplatex]{jsarticle}
\begin{document}
Hello world.
\end{document}
```

Compiling `foo.tex` on terminal by `uplatex foo.tex` goes successfully. On the other hand, invoking `uplatex` command on Atom by <kbd>Ctrl</kbd> + <kbd>Alt</kbd> + <kbd>B</kbd> shows "LaTeX compilation error" dialog in the status bar although `foo.tex` does not contain any errors.

![foo](https://cloud.githubusercontent.com/assets/13291527/18428663/34b83388-790a-11e6-9a5b-2102906267c8.gif)

The other problem is that since (u)pLaTeX generate DVI files instead of PDF, we cannot make PDF with `latex` package when we use (u)pLaTeX. It would be nice to invoke DVI drivers such as `dvipdfmx` or `dvips` in combination with `platex`/`uplatex` within Atom.

I think that the number of (u)pTeX users is quite smaller than that of other modern TeX engines, but I will greatly appreciate it if these problems are addressed.

---

For reference, this is my minimal `.latexmkrc` for upLaTeX. Hope this helps.

```perl
$pdf_mode = 3; # generate pdf via dvipdfmx
$latex = "uplatex -kanji=utf8 -file-line-error -halt-on-error -interaction=nonstopmode %O %S";
$dvipdf = "dvipdfmx %O -o %D %S";
```

**Comment by thomasjo** [comment] 2016-09-12 08:05
@yudai-nkt Thanks for the fantastic, thorough feature request 🙇 

In summary you essentially want two features
1. Support for `platex` and `uplatex`.
2. The ability to pipe DVI output through e.g. `dvipdfmx`, `dvips`, etc.

We'll investigate both requests. Myself and @yitzchak have started some thought processes around refactoring the current build infrastructure, possibly introducing the notion of a build pipeline. Feature 2 could easily be implemented in a pipeline scheme.

**Comment by yudai-nkt** [comment] 2016-09-12 09:06
> In summary you essentially want two features

Yes, your summary exactly gets my point (maybe I should have added a tl;dr section because large portion of the issue is about why I need these features).

I also forget noting the TeX distribution. Since (u)pTeX are not included in MikTeX, most Japanese LaTeX users use TeX Live or [W32TeX](http://w32tex.org/index.html). So, support for TeX Live (and accordingly latexmk) will be sufficient.

**Comment by yitzchak** [comment] 2016-09-12 14:50
I have reproduced the build failure resulting from `% !TEX program = uplatex`. We are currently passing this override to `latexmk` via a `-pdflatex=uplatex` command line argument. UpLaTeX is not a pdflatex derivative, so it needs to be passed to `latexmk` via a `-latex=uplatex` argument.

**Comment by yudai-nkt** [comment] 2016-09-12 15:08
Now I understand why the build fails. The error dialog does not appear when the output format in the settings menu is set to dvi. However, this workaround in turn breaks the availability of other engines like pdfTeX. There seems to be no compatibility with PDF-output engines and DVI-output ones in the current version as the package only provides global setting regarding the output format.

**Comment by yitzchak** [comment] 2016-09-20 12:05
@yudai-nkt I noticed that you are using the `-kanji=utf8` option. Is this required or will `uplatex` guess the encoding without it?

**Comment by yudai-nkt** [comment] 2016-09-20 12:52
@yitzchak It's not actually required, just a remains of when I used pLaTeX where explicit designation was preferred.

upTeX that is bundled with TeX Live does not have a scheme of guessing the input encoding, but the default encoding is set to UTF-8 in all platforms i.e., Windows, OS X, and Linux. In case of pTeX, that's another story. pTeX in TeX Live also doesn't guess the input encoding, and the different OSs have different default from among [EUC-JP](https://en.wikipedia.org/wiki/Extended_Unix_Code#EUC-JP), [SHIFT_JIS](https://en.wikipedia.org/wiki/Shift_JIS) and UTF-8. That's why I liked being explicit.

**Comment by yitzchak** [comment] 2016-09-29 10:42
@yudai-nkt #221 is basically feature complete. Would you be willing to do a checkout of the `latex-engine` branch and test it out?

**Comment by yudai-nkt** [comment] 2016-09-29 14:26
@yitzchak I've just carried out a small test with the sample code in the opening comment and it seems working well. I can also use other three engines that can directly produce PDF. When `openResultAfterBuild` is set to `true`, however, `build`-ing upLaTeX document opens the corresponding DVI file. Animated GIF below shows what happens when `alwaysOpenResultInAtom` is set to `true`. I would find it more convenient to preview PDF files rather than DVI.

Thank you so much for tackling this issue and feel free to tell me if there is anything else I can check!

![opendvi](https://cloud.githubusercontent.com/assets/13291527/18957153/f36f8312-8698-11e6-81e3-aee1ea06d741.gif)

**Comment by yitzchak** [comment] 2016-09-29 14:32
@yudai-nkt Thank you for trying it out. Much appreciated!

When you ran the build what was the output format set to in your settings page?

**Comment by yudai-nkt** [comment] 2016-09-29 14:37
@yitzchak Output Format is set to pdf. The `latex` part of my `~/.atom/config.cson` is as follows.

```coffeescript
  latex:
    alwaysOpenResultInAtom: true
```

**Comment by yitzchak** [comment] 2016-09-29 14:43
@yudai-nkt Can you try removing the `program` override and select `uplatex` as the engine in the settings page? There should be a DVI producer option also.

**Comment by yitzchak** [comment] 2016-09-29 14:45
@yudai-nkt 'uplatex' should show up in the engine drop down, BTW.

**Comment by yudai-nkt** [comment] 2016-09-29 15:01
@yitzchak  With the changes you mentioned, the package still opens a DVI file.

![opendvi2](https://cloud.githubusercontent.com/assets/13291527/18959379/e9fe783a-86a0-11e6-8967-a098692f7fc0.gif)

**Comment by yitzchak** [comment] 2016-09-29 15:12
@yudai-nkt I think have reproduced it.

Also, would a `Kanji Encoding` option to set `--kanji=xyz` be useful?

**Comment by yitzchak** [comment] 2016-09-29 15:29
@yudai-nkt I just pushed a commit that resolved it on my end. Looks like `latexmk` uses relative paths in the file name database when there is no output directory set. Try it out and let me know if it resolves the issue. Thanks!

**Comment by yudai-nkt** [comment] 2016-09-29 15:43
@yitzchak Pulling the latest commit fixes the issue on my end too!

Regarding the encoding option, I personally don't need it as I always make text files in UTF-8.

**Comment by yitzchak** [comment] 2016-09-29 15:45
@yudai-nkt Awesome! :boom: Thanks for all the help. The screen shots were very useful.

**Comment by yudai-nkt** [comment] 2016-09-29 15:59
@yitzchak It's my pleasure and I'm the one to say thank you.  :smile:

**Comment by yitzchak** [comment] 2016-10-01 13:33
Feature has been merged! :boom:

**Closed by yitzchak** 2016-10-01 13:33 UTC
Labels: feature, help wanted, in progress

**Comment by yudai-nkt** [comment] 2016-10-01 15:04
Awesome!  :heart_eyes: Will spread the word about this amazing feature when it's released!

**Comment by yitzchak** [comment] 2016-10-05 19:00
@yudai-nkt New version is out.
