### ISSUE TITLE
Package biblatex warning while using texify

### ISSUE THREAD

**Issue by lesenger** [thomasjo/atom-latex#185] opened 2016-06-16 07:12 UTC
I'm having troubles to build latex document using biblatex for my citations.
I use Windows, miktex2.9, texify as builder and pdflatex as engine.
Build does succeed without errors, but it throws warning:
Package biblatex Warning: Please (re)run Biber on the file: ...

Everything else in the final pdf is ok but citations is replaced with .bib file's keywords (Rivest1977, instead of Rivest et al. 1997)

I ran commands: `pdflatex doc && biber doc && pdflatex doc` directly from command line and pdf compiled as it should.

Is the problem with texify? When I'm using mac and latexmk as builder I have no problems.
Is it possible to fix this with atom-latex custom engine option? I'm not so sure how to use that
custom engine possibility.

**Comment by lesenger** [comment] 2016-06-29 06:17
I couldn't figure out how to fix this with miktex so I just installed texlive on windows and used latexmk as builder. Seems to work fine that way.

**Comment by karyon** [comment] 2016-08-18 09:26
i experience this as well and would like to see this fixed! i'd like to help if possible, just tell me how...

**Comment by yitzchak** [comment] 2016-09-07 00:56
I have reproduced this. It looks like `texify` does not know about BibTeX/Biber without the environment variable `BIBTEX=biber` being set. I suspect this is being done without the user's knowledge in editors like TeXstudio. I'll get PR prepared soon.

**Comment by yitzchak** [comment] 2016-09-07 15:27
This should be fixed via #208 and in the next release.

**Comment by karyon** [comment] 2016-09-15 08:32
unfortunately, i still get this warning in 0.36 with xetex and texify and new references are not resolved.

**Comment by yitzchak** [comment] 2016-09-15 13:28
Ok. Let me see it I can reproduce with `xetex`. Do you have a sample document?

**Comment by karyon** [comment] 2016-09-15 19:02
```
\documentclass{article}

\usepackage{fontspec}

\usepackage[backend=biber, natbib=true]{biblatex}

\addbibresource{foo-thesis.bib}

\begin{document}

a citation: \cite{segovia2006non}. and another one would be \citet{laine2007incremental}.

\end{document}

```

and the bibfile
```
@inproceedings{segovia2006non,
  title={Non-interleaved deferred shading of interleaved sample patterns},
  author={Segovia, Benjamin and Iehl, Jean Claude and Mitanchey, Richard and P{\'e}roche, Bernard},
  booktitle={SIGGRAPH/EUROGRAPHICS Conference on Graphics Hardware: Proceedings of the 21 st ACM SIGGRAPH/Eurographics symposium on Graphics hardware: Vienna, Austria},
  volume={3},
  number={04},
  pages={53--60},
  year={2006}
}

@inproceedings{laine2007incremental,
 author = {Laine, Samuli and Saransaari, Hannu and Kontkanen, Janne and Lehtinen, Jaakko and Aila, Timo},
 title = {Incremental Instant Radiosity for Real-time Indirect Illumination},
 booktitle = {Proceedings of the 18th Eurographics Conference on Rendering Techniques},
 series = {EGSR'07},
 year = {2007},
 isbn = {978-3-905673-52-4},
 location = {Grenoble, France},
 pages = {277--286},
 numpages = {10},
 url = {http://dx.doi.org/10.2312/EGWR/EGSR07/277-286},
 doi = {10.2312/EGWR/EGSR07/277-286},
 acmid = {2383883},
 publisher = {Eurographics Association},
 address = {Aire-la-Ville, Switzerland, Switzerland},
}
```

as before, building this once with latexmk fixes the issue even for subsequent builds with texify.

**Comment by karyon** [comment] 2016-09-15 19:04
um, i just noticed it fails with pdflatex as well. couldn't test that before i made that minimal example...

let me know if i should debug that (if you do, give some instructions please :) )

**Comment by yitzchak** [comment] 2016-09-15 19:57
I am starting to think this is an incompatibility between `texify` and `biblatex`. When I run the following from the command line I still get `Package biblatex Warning: Please (re)run Biber on the file:`.

```
set BIBTEX=biber
texify --pdf --engine=xetex foo.tex
```

**Comment by karyon** [comment] 2016-09-15 20:19
yeah, i get the same. found a related problem here: https://github.com/SublimeText/LaTeXTools/issues/637 but didn't understand what they did to fix it...

**Comment by yitzchak** [comment] 2016-09-15 21:07
As I read it I do not think they fixed it. `SimpleBuilder` is their own builder, so they just switched to that. The builder for `latexmk` and `texify` is [`TraditionalBuilder`](https://github.com/SublimeText/LaTeXTools/blob/master/builders/traditionalBuilder.py) and there is no mention of BibTeX in the code.

**Comment by yitzchak** [comment] 2016-09-19 19:32
I am closing this issue, because we are deprecating support for texify. Current functionality will be maintained during a phase out period, but no new functionality will be added. Please consider switch to latexmk as your builder. Please see [Using latexmk on MiKTeX](https://github.com/thomasjo/atom-latex/wiki/Using-latexmk-on-MiKTeX) for installation documentation.

**Closed by yitzchak** 2016-09-19 19:32 UTC
Labels: miktex, windows

**Comment by gilbertohasnofb** [comment] 2017-10-24 22:56
I was also having this problem on Linux but installing `latexmk` did the trick.
