### ISSUE TITLE
Settings don't seem to be taken into account

### ISSUE THREAD

**Issue by andrewjamescollett** [thomasjo/atom-latex#110] opened 2015-08-12 14:59 UTC
Hi. I've been using this for a bit, and I can say, nice work!

I'm using atom on windows, with tex-live installed. 

I'm struggling to get the settings for latex to have an effect. I am trying to compile a .tex that needs luatex or xelatex, which I am told in the latex .log, but after changing the setting, the same error occurs.  

Is there any useful data I can give? I also noticed that the settings are in the config:

```
"*":
  "exception-reporting":
    userId: ""
  welcome:
    showOnStartup: false
  core:
    themes: [
      "one-dark-ui"
      "solarized-dark-syntax"
    ]
  latex:
    engine: "lualatex"
  editor:
    invisibles: {}
    softWrap: true
    fontSize: 15
  "spell-check":
    grammars: [
      "text.tex.latex"
    ]
```

**Comment by thomasjo** [comment] 2015-08-13 05:56
I just tested a simple example document
``` latex
\documentclass{article}

\begin{document}
  the standard approximation $\pi = \directlua{tex.sprint(math.pi)}$
\end{document}
```

and it built as expected when I set `engine: "lualatex"`. Is luatex properly installed and working on your system? Here's the command that got executed when I built my example, perhaps you could execute an equivalent command manually from a console to verify that luatex works;
``` sh
latexmk -interaction=nonstopmode -f -cd -pdf -synctex=1 -file-line-error -shell-escape -lualatex "/Users/thomasjo/Scratch/tex/luatex-test/test.tex"
```

**Comment by andrewjamescollett** [comment] 2015-08-13 07:46
Thanks for the effort and reply.

It turns out I had a missing font, Fontin, so I jsut spend the last half hour trying to get that to work on windows. YaaaY. 

Anyway, what was throwing me off, is that in terminal, (I only tried this after your suggestion) it threw an error about the font not being there. In the .log file in atom though, it just told me the same thing as when I had pdfLatex selected. I.e. that I need Xe and Lua to use fontspec.

Anyway, not sure if that's helpful or anything. Problem sorted!

**Comment by thomasjo** [comment] 2015-08-14 10:00
Glad your problem was resolved!

Is there any chance you can provide a minimal example and associated log file that reproduces the problem? Even the tiniest "sliver" that could help me reproduce the problem would be extremely useful. Unfortunately I cannot fix the potential, underlying problem unless I can reproduce it.

Thanks in advance :bow:

**Comment by andrewjamescollett** [comment] 2015-08-14 14:49
I'm actually having difficulty reproducing the issue. 

Here's what I think happened. I will attach some code afterwards.

I think i tried to compile with pdflatex, then, after seeing it fail, I changed the engine, but forgot to delete all the output files. Thus, after changing to xelatex or lua, and building, it told me the same error. I tested it now, that if I delete all the output files, it compiles correctly. This isn't consistent though. It seems to clean itself fine... sometimes...

Summary:
To reproduce: (Not always it seems)
* Copy the below code into file
* With pdfLatex as engine, try build
* observe error 'you need xelatex....'
* change engine, and try rebuild
* observe the same error, maybe

Code:
```
\documentclass[a4paper,10pt]{article}

\usepackage{fontspec} % For loading fonts

\defaultfontfeatures{Mapping=tex-text}
\setmainfont[Path = fonts/,
  UprightFont = *-Regular.ttf,
  BoldFont = *-Bold.ttf,
  ItalicFont = *-Italic.ttf,
  SmallCapsFont = Fontin-SmallCaps.ttf]
  {Fontin} % Main document font

\begin{document}
  hello world
\end{document}
```

As I said above, this doesn't always happen. I don't quite understand how it can be inconsistent. Maybe having another file focused when you change the setting does something, maybe not. Can you reproduce the behavior with this code? Like I said. Sometimes for me.

**Comment by andrewjamescollett** [comment] 2015-08-14 14:53
* How do you check for files to clean? 
* Do you clean before each build? Or so you somehow keep track of what was built last? 
* Maybe it would be good to clean after each build too? As an option?

**Comment by thomasjo** [comment] 2015-08-17 07:48
@andrewjamescollett Good investigative work! :mag: The problem is that the build process relies on `latexmk` to do handle the "cleaning". Basically it tries to determine if the document, or anything referenced by it, has changed and if it has, it essentially does a rebuild of the necessary resources. Problem is that changing the build parameters, in this case the engine, does not trigger a rebuild.

Possible solution from our end would be to track config changes (at least changes to engine parameters), and automatically invoke e.g. the *Clean* command prior to *Build* if necessary. Another option is to introduce a new *Rebuild* command that always does a clean prior to building. Then if the package configuration has changed in a way requiring a rebuild, we could redirect an invocation of *Build* to *Rebuild*.

I'll close this issue since your issue has been resolved, but I'll open a new issue for improving the build process based on our findings in this issue.

**Closed by thomasjo** 2015-08-17 07:48 UTC
Labels: needs reproduction, texlive, windows

**Comment by andrewjamescollett** [comment] 2015-08-20 09:07
@thomasjo 

Thanks!
Not sure if this is the right place to reply. But thought I'd give my 2 cents worth. 

Other than solving this particular issue, would it not also be a useful feature to choose what files to clean after a build? As an extra option for the user. I find the number of files lying around a bit messy.

Also, any bug investigations you need in future, I don't mind looking into! I'm final year Computer Science student, so this is stuff I'm into.

**Comment by thomasjo** [comment] 2015-08-21 15:28
> Other than solving this particular issue, would it not also be a useful feature to choose what files to clean after a build? As an extra option for the user. I find the number of files lying around a bit messy.

That's actually a great feature/enhancement request; post-build cleanup. The way I avoid the "problem" is by using the *Output Directory* functionality (I've got it configured to redirect output to `.output`) in conjunction with *Move Result to Source Directory*. But I definitely think some type of post-build cleanup makes a lot of sense.

> Also, any bug investigations you need in future, I don't mind looking into! I'm final year Computer Science student, so this is stuff I'm into.

Awesome! :bow:
