### ISSUE TITLE
Incompatible Packages

### ISSUE THREAD

**Issue by trentks** [thomasjo/atom-latex#375] opened 2017-05-20 03:44 UTC
Upon launching with this package enabled I am greeted with a bug:

[Enter steps to reproduce:]

1. Install and enable latex package
2. Relaunch atom
3. Can confirm disabling the latex package and relanching atom removes the error

**Atom**: 1.16.0 x64
**Electron**: 1.4.16
**OS**: "Manjaro Linux"
**Thrown From**: [incompatible-packages](https://github.com/atom/incompatible-packages) package 0.27.2

### Stack Trace

Uncaught Error: Invalid child node: undefined

```
At /usr/lib/atom/node_modules/incompatible-packages/node_modules/etch/lib/dom.js:25

Error: Invalid child node: undefined
    at Object.dom (/usr/lib/atom/node_modules/incompatible-packages/node_modules/etch/lib/dom.js:25:15)
    at /usr/lib/atom/node_modules/incompatible-packages/lib/incompatible-packages-component.js:203:31
    at Array.map (native)
    at IncompatiblePackagesComponent.renderIncompatibleModules (/usr/lib/atom/node_modules/incompatible-packages/lib/incompatible-packages-component.js:199:34)
    at IncompatiblePackagesComponent.renderIncompatiblePackage (/usr/lib/atom/node_modules/incompatible-packages/lib/incompatible-packages-component.js:152:63)
    at Array.map (native)
    at IncompatiblePackagesComponent.renderIncompatiblePackageList (/usr/lib/atom/node_modules/incompatible-packages/lib/incompatible-packages-component.js:128:35)
    at IncompatiblePackagesComponent.render (/usr/lib/atom/node_modules/incompatible-packages/lib/incompatible-packages-component.js:79:14)
    at updateSync (/usr/lib/atom/node_modules/incompatible-packages/node_modules/etch/lib/component-helpers.js:99:34)
    at /usr/lib/atom/node_modules/incompatible-packages/node_modules/etch/lib/component-helpers.js:72:7
    at DefaultScheduler.performUpdates (/usr/lib/atom/node_modules/incompatible-packages/node_modules/etch/lib/default-scheduler.js:48:34)
```

### Commands

```
```

### Non-Core Packages

```
latex 0.43.0 
```

This is a fresh install of manjaro kde, with atom 1.16.0 x64 and latex 0.43.0. There are no other non-default atom-packages. This all works fine on my laptop running manjaro i3, with atom 1.16.0 x64 and latex 0.43.0.

**Comment by yitzchak** [comment] 2017-05-20 10:33
This is probably related to #360.

**Comment by tomrunia** [comment] 2017-05-29 17:31
Same problem on MacOS Sierra with Atom 1.17.2 and latex 0.43.0

**Comment by yitzchak** [comment] 2017-06-14 12:15
@tomrunia @trentks Just released v0.44.0, can you verify that problem still exists after updating?

**Comment by danielleontiev** [comment] 2017-07-26 22:06
Atom 1.18.0.
Same problem. Click "rebuild button" helps but latex package keep saying it can be upgraded to version > then 0.44.0 but cannot because of my atom version

**Comment by yitzchak** [comment] 2017-07-26 23:03
@danielleontiev You probably need v0.44.0 but not v0.44.1 since it requires Atom 1.19.0. Try uninstalling the latex package then do `apm install latex@0.44.0` from the command line.

**Comment by danielleontiev** [comment] 2017-07-26 23:06
@yitzchak It works, thanks

**Comment by yitzchak** [comment] 2017-07-26 23:07
@danielleontiev Awesome!

**Comment by mfalt** [comment] 2017-08-10 09:09
I also get the "Incompatible Packages" error
"Some installed packages could not be loaded because they contain native modules that were compiled for an earlier version of Atom."
"build@unknown – Cannot find module '/local/home/mattiasf/.atom/packages/latex/node_modules/abstract-socket/build'"
when I updated to atom "1.19.0" and atom-latex "0.45.0".
Rebuilding doesn't help.

**Comment by yitzchak** [comment] 2017-08-10 09:57
@mfalt What OS are you on?

**Comment by mfalt** [comment] 2017-08-10 10:00
Fedora 24 or 25, can verify in an hour. Everything worked fine before
updating these packages.

**Comment by yitzchak** [comment] 2017-08-10 10:02
@mfalt  What PDF viewer do you use?

**Comment by mfalt** [comment] 2017-08-10 10:21
Evince

**Comment by yitzchak** [comment] 2017-08-10 10:48
@mfalt I would try uninstalling `latex` and doing a fresh install. From the command line:

```bash
apm uninstall latex
apm install latex
cd ~/.atom/packages/latex
apm rebuild
```

I don't see a `--verbose` option on `apm rebuild` but maybe we will get some more info or maybe something has been corrupted. If this doesn't work I'll start trying to research/reproduce the issue. I have not seen it yet on Arch.

**Comment by mfalt** [comment] 2017-08-10 11:15
Update:
I'm actually running Fedora 23.
I tried running `make` in folder `/local/home/mattiasf/.atom/packages/latex/node_modules/abstract-socket/build'` and got the error `make: *** No rule to make target '../../../../../../../local/home/mattiasf/.atom/.node-gyp/.node-gyp/iojs-1.6.9/common.gypi', needed by 'Makefile'.  Stop.`
so I decided to `dnf install node-gyp`. After rebuilding latex in atom it said everything went fine and it works after restarting atom now.
I did several tries in rebuilding and restarting before installing `node-gyp` so maybe this is a clue.

**Comment by yitzchak** [comment] 2017-08-10 11:38
@mfalt Glad you got it working!

**Comment by yitzchak** [comment] 2017-09-27 10:14
Closing. Will reopen if needed.

**Closed by yitzchak** 2017-09-27 10:14 UTC
Labels: needs reproduction
