### ISSUE TITLE
magic comments don't work

### ISSUE THREAD

**Issue by beingalink** [thomasjo/atom-latex#108] opened 2015-08-03 15:51 UTC
"% !TEX root = " points to the main tex file that includes all the others. The atom-latex package doesn't seem to be able to understand that since it starts to compile the included file (which is the active file I work on) instead of the main file.

**Comment by thomasjo** [comment] 2015-08-03 18:59
It should work, there are even tests that ensure the feature works as intended (see [magic-parser-spec.js](https://github.com/thomasjo/atom-latex/blob/v0.25.0/spec/parsers/magic-parser-spec.js)).

One thing to ensure is that the "magic comment" is on the first line of the file. If the comment is on the first line, and this still doesn't work, it would be really great if you could link to a Gist or some such with a minimal example that reproduces the problem.

**Comment by beingalink** [comment] 2015-08-03 20:26
You were right. Putting "% !TEX root = " in the first line fixed it. Is "% !TEX root = " the only magic comment the parser can interpret? There are several more ( http://tex.stackexchange.com/a/78103 ) and it would be nice if these could be recognized independently from the position. For example, the header of my file looks like this:

%!TEX TS-program = xelatex
%!TEX encoding = UTF-8 Unicode
%!TEX root = Hausarbeit_Renten_D_GB.tex

**Comment by thomasjo** [comment] 2015-08-03 20:30
The parser itself grabs all of them, but right now only `root` is being used. I guess I should expand the parser to ensure that it can handle your example (even if we're not using e.g. `TS-program` yet).

**Comment by thomasjo** [comment] 2015-08-03 20:31
I'll close this since the root problem has been resolved, but I'll keep it in mind with regards to future enhancements.

**Closed by thomasjo** 2015-08-03 20:31 UTC

**Comment by beingalink** [comment] 2015-08-03 20:56
Thank you for your quick response to my problem! I appreciate that and wish you well for the future.
