### ISSUE TITLE
Build failed with module abstract-socket

### ISSUE THREAD

**Issue by thematdev** [thomasjo/atom-latex#544] opened 2020-11-14 09:55 UTC
I have upgraded Atom to 1.53.0 and have issue with latex package.
`abstract-socket@2.1.1 – The module '/home/thematdev/.atom/packages/latex/node_modules/abstract-socket/build/Release/bindings.node' was compiled against a different Node.js version using NODE_MODULE_VERSION 70. This version of Node.js requires NODE_MODULE_VERSION 73. Please try re-compiling or re-installing the module (for instance, using `npm rebuild` or `npm install`).`
I've tried `npm rebuild`, `npm uninstall` then `npm install` but it doesn't help.
Are there any fixes?

**Comment by thematdev** [comment] 2020-11-14 09:59
**OS**: Arch Linux
I've installed Atom from AUR.

**Comment by thomasjo** [comment] 2020-11-16 12:43
Duplicate of #542

**Closed by thomasjo** 2020-11-16 12:43 UTC
