### ISSUE TITLE
Synctex not working with Output-Directory enabled

### ISSUE THREAD

**Issue by M4a1x** [thomasjo/atom-latex#155] opened 2015-12-07 18:04 UTC
Hey there,
I'm on Windows 10 - 64bit with Atom 1.2.4, MikTex 2.9 and SumatraPDF 3.1.1.
When enabling the Output-Directory **and the "Move Result to Source Directory" checkbox**\*, SumatraPDF doesn't get refreshed after a successful LaTeX-Build. The corressponding lines blink blue - as expected, but the text doesn't change/update. 
When disabling Output-Directory (or the move) everything works as expected.
The Problem is limited to latexmk, since the Output Directory get's disabled upon using texify. 

Possible solution could be not to move the files, but to copy just the pdf instead and to open the file inside the output folder with SumatraPdf... This seems to work - at least on my machine.

\***Edit**: It works when only using the Output directory. Doesn't work with move enabled.

**Comment by thomasjo** [comment] 2016-01-27 21:46
Are any other Windows users able to reproduce this? This works as expected on OS X and Linux, so I'm guessing this might be some slightly esoteric problem with latexmk on Windows.

**Comment by yitzchak** [comment] 2016-10-13 20:50
Closing due to lack of reproduction. Will reopen if needed.

**Closed by yitzchak** 2016-10-13 20:50 UTC
Labels: miktex, needs reproduction, windows
